import { bigint, date, pgTable, text, timestamp, uuid } from "drizzle-orm/pg-core";
import { assignments } from "./assignments";
import { drivers } from "./drivers";
import { organisations } from "./organisations";
import { paymentMethodEnum } from "./enums";

/**
 * One row per assignment per rent period, generated by the weekly cron
 * (§5). Append-only. Waiving requires a reason and is always manual —
 * nothing auto-waives.
 */
export const rentCharges = pgTable("rent_charges", {
  id: uuid("id").defaultRandom().primaryKey(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organisations.id),
  assignmentId: uuid("assignment_id")
    .notNull()
    .references(() => assignments.id),
  driverId: uuid("driver_id")
    .notNull()
    .references(() => drivers.id),
  periodStart: date("period_start").notNull(),
  periodEnd: date("period_end").notNull(),
  amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
  waivedCents: bigint("waived_cents", { mode: "number" }).notNull().default(0),
  waiveReason: text("waive_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Append-only. A correction is a new row, or a void with a reason —
 * never an in-place edit or delete (§4).
 */
export const payments = pgTable("payments", {
  id: uuid("id").defaultRandom().primaryKey(),
  orgId: uuid("org_id")
    .notNull()
    .references(() => organisations.id),
  driverId: uuid("driver_id")
    .notNull()
    .references(() => drivers.id),
  assignmentId: uuid("assignment_id")
    .notNull()
    .references(() => assignments.id),
  amountCents: bigint("amount_cents", { mode: "number" }).notNull(),
  method: paymentMethodEnum("method").notNull(),
  reference: text("reference"),
  paidAt: timestamp("paid_at", { withTimezone: true }).notNull().defaultNow(),
  periodStart: date("period_start"),
  periodEnd: date("period_end"),
  proofStorageKey: text("proof_storage_key"),
  voidedAt: timestamp("voided_at", { withTimezone: true }),
  voidReason: text("void_reason"),
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
});
